language: c

env:
  global:
    secure: "V31gtcRefpWs6rqr4lD+kZzi3b2kOZFMNNfCeqUAx4QzSz5qEf+QPo4EzVwxTsq8ik88ElIMuKHC5Frw+IG3SWM67QsD6QDqqsjqsLqfEqU/hALxqdvO7Mc05MS/CUFB6mrVKwtiuYrsWaD3bdYuT1H/HIbZcOCcktfBXvLnrBVVqh1U8W2mTEOY4wLTczgIt0GLMKab2UtfVa7jd+0Sykg83sfJDajyqN1z4wxvz4BTlxjPtr5HYaqaF2+QTEBtHydBXl+2HIolEFfTGP7NuiGL5LTrOpeQPqgqXBs49iTBXvZXzoV74Ia8t5Zh1W4ID/1HDummI6tl2qY9KgpX3mkeAxm3IITNy3FYbjalW4tGEAR2oU7f18jxBrm68BU06eZMEB/QSGOqMZQxj73hoelRQe33GwBV9iMkBVXwHuEtKJrA6tmXdh/s4znjxoKKk7PnEey9gio8rAcZ7LzNTDX/cSAL1Sx4yGx3yIls9luTMw6G7zdYbFLQpzUyJuhRQXl45KxBGvxlfrac4iDjVXBw3riCOIzz1RwcvZ7DrSZVQW56eXRTA14+k5hot28jX4JHlMXA96zPGDxZOLEXuw2I7Pu6zwQZj73/o5yrTvql3FoJughNmYQBVw2SJAVquKyM9e1Qmr1F3d7apvhYJQ81CDoReYoLjsJsUto7Mrk="

matrix:
  include:
    ##
    # Test basic installation with different Travis environments
    ##
    # # Ubuntu 12.04 container build
    # - os: linux
    #   env: COMPONENTS=icc
    # # Ubuntu 12.04 VM
    # - os: linux
    #   env: COMPONENTS=icc
    # Ubuntu 14.04 VM
    - os: linux
      dist: trusty
      env: COMPONENTS=icc

    ##
    # Test individual components
    ##
    # # IPP
    # - os: linux
    #   sudo: false
    #   env: COMPONENTS="icc,ipp"
    # # TBB
    # - os: linux
    #   sudo: false
    #   env: COMPONENTS="icc,tbb"
    # # DAAL
    # - os: linux
    #   sudo: false
    #   env: COMPONENTS="icc,daal"
    # # MPI
    # - os: linux
    #   sudo: false
    #   env: COMPONENTS="icc,mpi"
    # # Fortran
    # - os: linux
    #   sudo: false
    #   env: COMPONENTS="icc,ifort"
    # # Fortran + MKL
    # - os: linux
    #   sudo: false
    #   env: COMPONENTS="icc,ifort,mkl"
    # # Fortran + MPI
    # - os: linux
    #   sudo: false
    #   env: COMPONENTS="icc,ifort,mpi"

    # # Everything (for debugging without taxing Travis too heavily)
    # - os: linux
    #   sudo: false
    #   env: COMPONENTS="icc,ifort,mpi,daal,ipp,tbb,mkl"
before_install:
  - ./install-icc-iss.sh --components "${COMPONENTS}"
  - source ~/.bashrc
script:
  # C compiler
  - '[[ "${COMPONENTS}" != *"icc"* ]] || (icc -std=c99 test/test.c -o test/test-c99 && ./test/test-c99)'
#  # C++ compiler
#   - '[[ "${COMPONENTS}" != *"icc"* ]] || (icpc -std=c++11 test/test.cxx -o test/test-c++11 && ./test/test-c++11)'
#   # Cilk support
#   - '[[ "${COMPONENTS}" != *"icc"* ]] || (icc -std=c99 test/test-cilk.c -o test/test-cilk && ./test/test-cilk)'
#   # Fortran 90 compiler
#   - '[[ "${COMPONENTS}" != *"ifort"* ]] || (ifort -std08 -fpp test/test.f90 -o test/test-f90 && ./test/test-f90)'
#   # MPI-3
#   - '[[ "${COMPONENTS}" != *"mpi"* ]] || (mpiicc -std=c99 test/test-mpi.c -o test/test-mpi && ./test/test-mpi)'
#   # IPP
#   - '[[ "${COMPONENTS}" != *"ipp"* ]] || (icc -std=c99 -ipp test/test-ipp.c -o test/test-ipp && ./test/test-ipp)'
#   # DAAL
#   - '[[ "${COMPONENTS}" != *"daal"* ]] || (icpc -std=c++11 -daal test/test-daal.cxx -o test/test-daal && ./test/test-daal)'
#   # TBB
#   - '[[ "${COMPONENTS}" != *"tbb"* ]] || (icpc -std=c++11 -tbb test/test-tbb.cxx -o test/test-tbb && ./test/test-tbb)'
#   # MKL CBLAS
#   - '[[ "${COMPONENTS}" != *"mkl"* ]] || (icc -std=c99 -mkl test/test-mkl.c -o test/test-mkl && ./test/test-mkl)'
#   # Fortran MKL
#   - '[[ "${COMPONENTS}" != *"ifort"* || "${COMPONENTS}" != *"mkl"* ]] || (ifort -std08 -mkl test/test-mkl.f90 -o test/test-mkl-fortran && ./test/test-mkl-fortran)'
#   # Fortran MPI-2
#   - '[[ "${COMPONENTS}" != *"ifort"* || "${COMPONENTS}" != *"mkl"* || "${COMPONENTS}" != *"mpi"* ]] || (mpiifort -std08 test/test-mpi.f90 -o test/test-mpi-fortran && ./test/test-mpi-fortran)'
#   # Fortran 2008 MPI-3
#   - '[[ "${COMPONENTS}" != *"ifort"* || "${COMPONENTS}" != *"mkl"* || "${COMPONENTS}" != *"mpi"* ]] || (mpiifort -std08 test/test-mpi-f08.f90 -o test/test-mpi-f08 && ./test/test-mpi-f08)'

# after_script:
#   - '[[ ! -z "${INTEL_INSTALL_PATH}" ]] && uninstall_intel_software'

notifications:
  email:
    on_success: change
    on_failure: change
